/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{public_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_sessions__public_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{public_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Message */
        post: operations["message_api_sessions__public_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{public_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize */
        post: operations["finalize_api_sessions__public_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook */
        post: operations["webhook_webhooks_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alternative */
        Alternative: {
            journey: components["schemas"]["Journey"];
            stay: components["schemas"]["Stay"];
            known_total?: components["schemas"]["Money"] | null;
            /**
             * Price Coverage
             * @default 0
             */
            price_coverage: number;
            /** Summary */
            summary: string;
        };
        /** Brief */
        Brief: {
            /** Fixture Ids */
            fixture_ids: string[];
            /**
             * Origin City
             * @default London
             */
            origin_city: string;
            /**
             * @default {
             *       "adults": 1,
             *       "child_ages": [],
             *       "rooms": 1
             *     }
             */
            travellers: components["schemas"]["Party"];
            /**
             * Budget Tier
             * @default value
             * @enum {string}
             */
            budget_tier: "budget" | "value" | "comfort";
            /**
             * Flexibility
             * @default day_either_side
             * @enum {string}
             */
            flexibility: "tight" | "day_either_side" | "two_days";
            /**
             * Windows
             * @default []
             */
            windows: components["schemas"]["Window"][];
            /**
             * Extra Instructions
             * @default
             */
            extra_instructions: string;
            /**
             * Private Room
             * @default false
             */
            private_room: boolean;
            /**
             * Private Bathroom
             * @default false
             */
            private_bathroom: boolean;
            /** Transport Mode */
            transport_mode?: ("flight" | "rail") | null;
        };
        /** ChatTurn */
        ChatTurn: {
            /** Id */
            id: string;
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Command */
        Command: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Expected Revision */
            expected_revision?: number | null;
        };
        /** CreateSession */
        CreateSession: {
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            brief: components["schemas"]["Brief"];
        };
        /** Evidence */
        Evidence: {
            /**
             * Provider
             * @default SearchApi
             */
            provider: string;
            /** Underlying Source */
            underlying_source: string;
            /** Source Url */
            source_url?: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
        };
        /** Fixture */
        Fixture: {
            /** Id */
            id: string;
            /** Opponent */
            opponent: string;
            /** City */
            city: string;
            /** Timezone */
            timezone: string;
            /**
             * Kickoff At
             * Format: date-time
             */
            kickoff_at: string;
            /** Venue */
            venue: string;
            /**
             * Venue Status
             * @default provisional
             * @enum {string}
             */
            venue_status: "provisional" | "confirmed";
            /** Source Url */
            source_url: string;
            /**
             * Source Checked At
             * Format: date-time
             */
            source_checked_at: string;
            /** Catalog Version */
            catalog_version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Itinerary */
        Itinerary: {
            /** Revision */
            revision: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Trips */
            trips: components["schemas"]["Trip"][];
            /**
             * Caveats
             * @default [
             *       "Prices may have changed since retrieval. Confirm the full price before booking.",
             *       "Match tickets and travel to/from your London departure hub are not included."
             *     ]
             */
            caveats: string[];
            /**
             * Ranking Policy Version
             * @default 1
             */
            ranking_policy_version: string;
        };
        /** Journey */
        Journey: {
            /** Id */
            id: string;
            /** Route Id */
            route_id: string;
            /** Outbound */
            outbound: components["schemas"]["Leg"][];
            /** Inbound */
            inbound: components["schemas"]["Leg"][];
        };
        /** Leg */
        Leg: {
            /**
             * Kind
             * @default transport
             * @constant
             */
            kind: "transport";
            /** Id */
            id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "flight" | "rail";
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /**
             * Departs At
             * Format: date-time
             */
            departs_at: string;
            /**
             * Arrives At
             * Format: date-time
             */
            arrives_at: string;
            /** Operator */
            operator: string;
            /**
             * Service Number
             * @default
             */
            service_number: string;
            offer: components["schemas"]["Offer"];
            quote?: components["schemas"]["Quote"] | null;
            /**
             * Caveats
             * @default []
             */
            caveats: string[];
        };
        /** MessageCommand */
        MessageCommand: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Expected Revision */
            expected_revision?: number | null;
            /** Text */
            text: string;
        };
        /** Money */
        Money: {
            /** Minor Units */
            minor_units: number;
            /** Currency */
            currency: string;
        };
        /** Offer */
        Offer: {
            /** Id */
            id: string;
            /** Booking Url */
            booking_url?: string | null;
            /**
             * Link Kind
             * @default contextual_search
             * @enum {string}
             */
            link_kind: "direct" | "contextual_search" | "generic_search";
            /** Seller */
            seller?: string | null;
            evidence: components["schemas"]["Evidence"];
            /** Search Fingerprint */
            search_fingerprint: string;
        };
        /** Party */
        Party: {
            /**
             * Adults
             * @default 1
             */
            adults: number;
            /**
             * Child Ages
             * @default []
             */
            child_ages: number[];
            /**
             * Rooms
             * @default 1
             */
            rooms: number;
        };
        /** Quote */
        Quote: {
            /** Id */
            id: string;
            amount: components["schemas"]["Money"];
            /**
             * Scope
             * @enum {string}
             */
            scope: "round_trip" | "leg" | "stay" | "night" | "unknown";
            /**
             * Unit
             * @enum {string}
             */
            unit: "party" | "person" | "room" | "bed" | "unknown";
            priced_party?: components["schemas"]["Party"] | null;
            /**
             * Taxes
             * @default unknown
             * @enum {string}
             */
            taxes: "included" | "excluded" | "unknown";
            additional_taxes?: components["schemas"]["Money"] | null;
            /** Payment Currency */
            payment_currency?: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Caveats
             * @default []
             */
            caveats: string[];
        };
        /** Receipt */
        Receipt: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Accepted */
            accepted: boolean;
            /**
             * Reason
             * @default accepted
             * @enum {string}
             */
            reason: "accepted" | "busy" | "closed" | "stale";
        };
        /** Snapshot */
        Snapshot: {
            /**
             * Development Mode
             * @default false
             */
            development_mode: boolean;
            /**
             * Public Session Id
             * Format: uuid
             */
            public_session_id: string;
            /**
             * Origin City
             * @default London
             */
            origin_city: string;
            /**
             * State Revision
             * @default 0
             */
            state_revision: number;
            /**
             * Phase
             * @default created
             * @enum {string}
             */
            phase: "created" | "researching" | "draft_ready" | "revising" | "finalizing" | "emailed" | "failed" | "email_failed";
            /**
             * Progress Message
             * @default Checking routes from London…
             */
            progress_message: string;
            itinerary?: components["schemas"]["Itinerary"] | null;
            /**
             * Transcript Tail
             * @default []
             */
            transcript_tail: components["schemas"]["ChatTurn"][];
            /** Active Turn Id */
            active_turn_id?: string | null;
            /** Last Committed Turn Id */
            last_committed_turn_id?: string | null;
            /**
             * Email Deadline
             * Format: date-time
             */
            email_deadline: string;
            /**
             * Interaction Deadline
             * Format: date-time
             */
            interaction_deadline: string;
            /**
             * Follow Ups Remaining
             * @default 10
             */
            follow_ups_remaining: number;
            /** Finalization Reason */
            finalization_reason?: ("manual" | "inactivity" | "limit" | "planning_failed") | null;
            /** Email Kind */
            email_kind?: ("itinerary" | "failure_notice") | null;
            /**
             * Email Status
             * @default not_requested
             * @enum {string}
             */
            email_status: "not_requested" | "pending" | "sent" | "failed";
            /** Email Provider Id */
            email_provider_id?: string | null;
        };
        /** Stay */
        Stay: {
            /**
             * Kind
             * @default stay
             * @constant
             */
            kind: "stay";
            /** Id */
            id: string;
            /** Property Name */
            property_name: string;
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /** Room Description */
            room_description: string;
            /**
             * Bathroom
             * @default unknown
             * @enum {string}
             */
            bathroom: "private" | "shared" | "unknown";
            /**
             * Room Type
             * @default unknown
             * @enum {string}
             */
            room_type: "private" | "dorm" | "unknown";
            /** Max Guests */
            max_guests?: number | null;
            /** Review Score */
            review_score?: number | null;
            offer: components["schemas"]["Offer"];
            quote?: components["schemas"]["Quote"] | null;
            /**
             * Caveats
             * @default []
             */
            caveats: string[];
        };
        /** TransferGuidance */
        TransferGuidance: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Source Url */
            source_url: string;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
        };
        /** Trip */
        Trip: {
            fixture: components["schemas"]["Fixture"];
            journey?: components["schemas"]["Journey"] | null;
            stay?: components["schemas"]["Stay"] | null;
            known_total?: components["schemas"]["Money"] | null;
            /**
             * Price Coverage
             * @default 0
             */
            price_coverage: number;
            /**
             * Feasibility
             * @default needs_checks
             * @enum {string}
             */
            feasibility: "verified" | "needs_checks";
            /**
             * Gaps
             * @default []
             */
            gaps: string[];
            /** Summary */
            summary: string;
            /**
             * Transfers
             * @default []
             */
            transfers: components["schemas"]["TransferGuidance"][];
            /**
             * Alternatives
             * @default []
             */
            alternatives: components["schemas"]["Alternative"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Window */
        Window: {
            /** Fixture Id */
            fixture_id: string;
            /**
             * Earliest Departure
             * Format: date-time
             */
            earliest_departure: string;
            /**
             * Latest Return
             * Format: date-time
             */
            latest_return: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_api_sessions_post: {
        parameters: {
            query?: never;
            header: {
                "X-Submission-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_sessions__public_id__snapshot_get: {
        parameters: {
            query?: {
                after_revision?: number | null;
            };
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    message_api_sessions__public_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_api_sessions__public_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_webhooks_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    ready_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
}
